In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones((2,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
# Create an array of zeros with 2 rows and 10 columns

In [20]:
# divides 0 to 1 in 4 equal parts
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [22]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# makes an array of random numbers ranging from 0 to 1
np.random.rand(3,2)

array([[0.61945493, 0.35145876],
       [0.5656949 , 0.15007615],
       [0.29528543, 0.11634233]])

In [30]:
# makes an array of random numbers both +ve and -ve
np.random.randn(3,2)

array([[ 0.01128059, -0.9832047 ],
       [ 0.05576284, -0.03789791],
       [ 0.52953745,  1.15395502]])

In [33]:
# any random number between 34 and 99
np.random.randint(34,100)

80

In [34]:
# random numbers from 20 to 55 for 100 times
np.random.randint(20,56,100)

array([33, 44, 29, 51, 41, 39, 20, 31, 53, 28, 50, 20, 48, 54, 42, 27, 48,
       28, 36, 23, 46, 31, 29, 27, 28, 47, 40, 27, 29, 51, 47, 32, 49, 21,
       41, 21, 30, 42, 32, 27, 46, 36, 46, 39, 53, 30, 25, 38, 35, 20, 44,
       37, 50, 50, 55, 32, 37, 23, 55, 20, 45, 26, 32, 22, 35, 30, 25, 20,
       50, 50, 34, 33, 29, 30, 23, 38, 52, 45, 53, 49, 43, 44, 30, 28, 20,
       46, 33, 29, 20, 28, 48, 44, 25, 41, 54, 47, 34, 48, 47, 28])

In [35]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
rand_array=np.random.randint(0,100,20)
rand_array

array([64, 66, 78, 41, 42, 46, 30, 23,  9, 85,  8, 13, 83, 64,  3, 66, 18,
       59, 32, 86])

In [41]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
sample_array.reshape(3,7)

ValueError: ignored

In [43]:
rand_array.max()

86

In [44]:
# index of the max value
rand_array.argmax

19

In [45]:
sample_array.dtype

dtype('int64')

In [49]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
a=np.random.rand(2,3)
a

array([[0.88509004, 0.25892823, 0.38951562],
       [0.92806799, 0.44771768, 0.99568669]])

In [52]:
# T is the transpose
a.T

array([[0.88509004, 0.92806799],
       [0.25892823, 0.44771768],
       [0.38951562, 0.99568669]])

In [53]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
sample_array[-3]

18

In [55]:
sample_array[3:7]

array([13, 14, 15, 16])

In [57]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [66]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [68]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [69]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

***TWO DIMENSIONAL ARRAY***

In [70]:
import numpy as np

In [72]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [73]:
sample_matrix[0][2]

1

In [74]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [77]:
sample_matrix[2]

array([56, 76, 24,  7])

In [82]:
sample_matrix[:,2]

array([ 1, 21, 24])

In [81]:
# calling the third and second column index
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

***SELECTION TECHNIQUES***

In [84]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [85]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [86]:
np.exp(sample_array) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [87]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [88]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [89]:
np.max(sample_array)

19

In [90]:
np.min(sample_array)

1

In [91]:
np.argmax(sample_array)

18

In [92]:
np.argmin(sample_array)

0